config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', views.index , name ='index'),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail , name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name = 'question_create'),
    #path('finance/', views.finance, name = 'finance'),
    #path('finance/<int:finance_id>/', views.finance_detail, name = 'finance_detail'),
    path('kospi/', views.kospi , name = 'kospi'),
    path('kosdaq/', views.kosdaq , name = 'kosdaq'),
    path('Risk/', views.risk, name='risk'),
    path('kospi/<int:kospi_id>/', views.kospi_detail , name = 'kospi_detail'),
    path('kosdaq/<int:kosdaq_id>/', views.kosdaq_detail , name = 'kosdaq_detail'),    
    path('kospi/<int:id>/graph', views.graph , name = 'graph'),
    path('kosdaq/<int:id>/graph', views.graph , name = 'graph'),
]

pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class Finance(models.Model):
    Date= models.DateTimeField()
    Open = models.FloatField()
    High = models.FloatField()
    Low = models.FloatField()
    Close = models.FloatField()
    Volume = models.FloatField()
    Change = models.FloatField()

#코스피
class Kospi(models.Model):
    Symbol = models.IntegerField()
    Market = models.TextField()
    Name = models.TextField()

#코스닥
class Kosdaq(models.Model):
    Symbol = models.IntegerField()
    Market = models.TextField()
    Name = models.TextField()

#리스크
class Risk(models.Model):
    spread = models.FloatField()
    DXY = models.FloatField()
    Label = models.IntegerField()
    Date = models.TextField()

pybo/forms.py
from django import forms
from django.forms import widgets
from pybo.models import Finance, Question ,Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  
        label = {
            'subject':'제목',
            'content':'내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class FinanceForm(forms.ModelForm):
    class Meta:
        model = Finance
        fields = ['Date','Open','Close']
        labels = {
            'Date':'날짜',
            'Open':'시가',
            'Close':'종가'
        }

pybo/views.py
from datetime import datetime
from datetime import timedelta
from datetime import time
from django.shortcuts import get_object_or_404, render,get_list_or_404, redirect,HttpResponse
from django.contrib import messages
from django.db.models import Q
from numpy import datetime64, datetime_as_string
from .models import Question ,Finance, Kospi,Kosdaq,Risk
from .forms import QuestionForm, AnswerForm 
from django.core.paginator import Paginator
import FinanceDataReader as fdr
from bokeh.resources import CDN
from bokeh.embed import file_html
from bokeh.plotting import figure, output_file, show 
from bokeh.embed import components
from bokeh.layouts import gridplot
from bokeh.io import curdoc
import jinja2
import pandas as pd
from pandas._libs.tslibs.timestamps import Timestamp
from math import pi
import string
import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import RobustScaler
import investpy
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score


def index(request):
    curdoc().theme = 'dark_minimal'

    df1 = fdr.DataReader('KS11','2021-08-01')
    df2 = fdr.DataReader('KQ11','2021-08-01')
    
    df1 = df1.rename_axis('Date').reset_index()
    df2 = df2.rename_axis('Date').reset_index()


    #PLOT_OPTIONS = dict(plot_width=800, plot_height=300)
    #SCATTER_OPTIONS = dict(size=12, alpha=0.5)

    red = figure(title = 'KOSPI 종합주가지수',x_axis_type='datetime',width=650,height =400, tools='pan')
    red.line(df1['Date'], df1['Close'], color="red",line_width = 3)
    blue = figure(title = 'KOSDAQ 종합주가지수',x_axis_type='datetime',width=650,height =400, tools='pan')
    blue.line(df2['Date'], df2['Close'], color="blue",line_width = 3)

    script1, div1 = components(red)
    script2, div2 = components(blue)

    context = {'script1':script1,'div1':div1,'script2':script2,'div2':div2}
    return render(request,'pybo/home.html',context=context)


"""
def index(request):
    
    #pybo 목록 출력
    
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    question_list = Question.objects.order_by('-create_date')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)
"""
def detail(request, question_id):
    
    #pybo 내용 출력
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)  
    
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form= QuestionForm()
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

def finance(request):
    
    page = request.GET.get('page', '1') 

    finance_list = Finance.objects.order_by('-Date')
    paginator = Paginator(finance_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'finance_list': page_obj}
    return render(request,'pybo/finance_list.html',context)         #pybo/finance_list.html에 context 변수를 적용해서 넘겨줘라 
"""
def finance_detail(request,finance_id):
    finance_list = Finance.objects.get(id = finance_id)
    context ={'finance_list':finance_list}
    return render(request,'pybo/finance_detail.html',context)
"""
def kospi(request):
    page = request.GET.get('page', '1') 

    kospi_list = Kospi.objects.order_by('Symbol')
    search_key = request.GET.get('search_key') # 검색어 가져오기
    if search_key: # 만약 검색어가 존재하면
        kospi_list = kospi_list.filter(Name__icontains=search_key) # 해당 검색어를 포함한 queryset 가져오기

    paginator = Paginator(kospi_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'kospi_list': page_obj}
    return render(request,'pybo/kospi.html',context)

def kosdaq(request):
    page = request.GET.get('page', '1') 
    kosdaq_list = Kosdaq.objects.order_by('Symbol')
    search_key = request.GET.get('search_key') # 검색어 가져오기
    if search_key: # 만약 검색어가 존재하면
        kosdaq_list = kosdaq_list.filter(Name__icontains=search_key) # 해당 검색어를 포함한 queryset 가져오기

    paginator = Paginator(kosdaq_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'kosdaq_list': page_obj}
    return render(request,'pybo/kosdaq.html',context)


def kospi_detail(request,kospi_id):
    # 종목 정보
    Kospi_list = Kospi.objects.get(Symbol = kospi_id)

    kospi_id =str(kospi_id)
    # 종목 historic data
    if len(kospi_id) != 6:
        kospi_id = kospi_id.zfill(6)

    df = fdr.DataReader(kospi_id,'2021-09-01')
    df = df.sort_index(ascending=False)
    #차트 그리기
    
    #데이터 형 변환
    df.index = df.index.astype(str)
    df['Change'] *= 100
  
    # json 데이터로 변형
    json_records = df.reset_index().to_json(orient ='records')
    data = []
    data = json.loads(json_records)
    
    #페이지 설정
    page = request.GET.get('page', '1') 
    paginator = Paginator(df, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context ={'Kospi_list':Kospi_list ,'d': data}
    return render(request,'pybo/kospi_detail.html',context)

def kosdaq_detail(request,kosdaq_id):
   # 종목 정보
    Kosdaq_list = Kosdaq.objects.get(Symbol = kosdaq_id)

    kosdaq_id =str(kosdaq_id)
    # 종목 historic data
    if len(kosdaq_id) != 6:
        kosdaq_id = kosdaq_id.zfill(6)

    df = fdr.DataReader(kosdaq_id,'2021-09-01')
    df = df.sort_index(ascending=False )

    #데이터 형 변환
    df.index = df.index.astype(str)
    df['Change'] *= 100
  
    # json 데이터로 변형
    json_records = df.reset_index().to_json(orient ='records')
    data = []
    data = json.loads(json_records)
    
    #페이지 설정
    page = request.GET.get('page', '1') 
    paginator = Paginator(df, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context ={'Kosdaq_list':Kosdaq_list ,'d': data}
    return render(request,'pybo/kosdaq_detail.html',context)

def graph(request, id):

    id =str(id)   

    if len(id) != 6:
        id = id.zfill(6)
    
    df = fdr.DataReader(id,'2021-08-01')
    df = df.rename_axis('Date').reset_index()

    inc = df.Close > df.Open
    dec = df.Open > df.Close
    w = 12*60*60*1000 # half day in ms

    TOOLS = "pan,wheel_zoom,box_zoom,reset,save"
    
    p1 = figure(x_axis_type="datetime", tools=TOOLS, plot_width=1000, plot_height=500, title = "Candlestick with Volume")
    p1.xaxis.major_label_orientation = pi/4  
    p1.grid.grid_line_alpha=0.3
    p1.segment(df.Date, df.High, df.Date, df.Low, color="black")
    p1.vbar(df.Date[inc], w, df.Open[inc], df.Close[inc], fill_color="#F2583E", line_color="black")
    p1.vbar(df.Date[dec], w, df.Open[dec], df.Close[dec], fill_color="#3088f1", line_color="black")
   
    script, div = components(p1)

    return render(request, 'pybo/graph.html', {'script': script, 'div': div})

def risk(request):
    page = request.GET.get('page', '1')

    # 데이터 프레임으로 받기
    risk_list = Risk.objects.order_by('-id')
    risk_list_1 = Risk.objects.order_by('id').values()

    # 시간설정, 스케일러 설정
    td = datetime.today().strftime("%d" + "/" + "%m" + "/" + "%Y")  # 오늘 날짜
    yesterday = datetime.today() - timedelta(2)
    yesterday = yesterday.strftime("%d" + "/" + "%m" + "/" + "%Y")
    scaler = RobustScaler()
    day1 = []
    day1.append((datetime.today() + timedelta(240)).strftime("%Y" + "/" + "%m" + "/" + "%d"))
    day1.append((datetime.today() + timedelta(300)).strftime("%Y" + "/" + "%m" + "/" + "%d"))

    """ 미국 10년 국채 금리 """
    df = investpy.get_bond_historical_data(bond='U.S. 10Y', from_date=yesterday, to_date=td)
    data = pd.DataFrame(df)

    """미국 2년 국채 금리 """
    df1 = investpy.get_bond_historical_data(bond='U.S. 2Y', from_date=yesterday, to_date=td)
    data1 = pd.DataFrame(df1)

    """ 국채 10년물 - 국채 2년물 / 국채 스프레드 """
    spread = data.loc[:, 'Close'] - data1.loc[:, 'Close']

    """달러 인덱스 점수 매기기"""
    search_results = investpy.get_index_historical_data(index='US Dollar Index', country='United States', from_date=yesterday, to_date=td)
    DXY = search_results.loc[:, 'Close']  # 달러 인덱스의 종가

    spread['Date'] = spread.index

    today_ = pd.concat([spread, DXY], axis=1, keys=['spread', 'DXY'])
    today_['Date'] = today_.index

    today_1 = today_.iloc[[1], :]
    today_1['Label'] = 0

    #데이터 읽어 들여서 데이터프레임에 넣고 robustscaler 넣는다.
    data2 =pd.DataFrame(risk_list_1)
    # 합치고
    data2 = pd.concat([data2,today_1])
    # 스케일링진행
    data2[["spread", "DXY"]] = scaler.fit_transform(data2[["spread", "DXY"]])

    #모델설정
    model = KNeighborsClassifier(n_neighbors =3 , weights='distance', metric='euclidean')
    X = data2.iloc[:len(data2)-1, 1:3]         # X열
    y = data2.iloc[:len(data2)-1, [3]]         # 라벨링
    X_test_1 = data2.iloc[[len(data2) - 1], 1:3]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
        y_train, y_test = y.iloc[train_index, :], y.iloc[test_index, :]
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test_1)

templates/pybo/graph.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class = "container">
      {{div | safe}}
      {{div3| safe}}

    </div>
{% endblock %}

templates/pybo/kosdaq.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<form action="" method='GET'>
    <div class="row justify-content-end my-3" style="margin-bottom:15px;">
        <div class="col-4 input-group">
            <div class="input-group">
                <input type="text" class="form-control" name="search_key" value="{{ search_key }}"
                    placeholder="looking for...">
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search">
                </span>
            </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
</form>

<div class="row">
    <div id="video_list_search" class="col-md-12">
        {% for video in video_list %}
        <a href="/video/{{ video.id }}">
            <h4>{{ video.title }}</h4>
        </a>
        {% endfor %}
    </div>
</div>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>No.</th>
            <th>종목번호</th>
            <th>시장</th>
            <th>회사명</th>
        </tr>
        </thead>
        <tbody>
        {% if kosdaq_list %}
        {% for kosdaq in kosdaq_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{kosdaq.Symbol}}</td>
            <td>{{ kosdaq.Market }}</td>
            <td><a href="{% url 'pybo:kosdaq_detail' kosdaq.Symbol %}">{{ kosdaq.Name }}</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if kosdaq_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ kosdaq_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in kosdaq_list.paginator.page_range %}
        {% if page_number >= kosdaq_list.number|add:-5 and page_number <= kosdaq_list.number|add:5 %}
            {% if page_number == kosdaq_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if kosdaq_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ kosdaq_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

templates/pybo/kosdaq_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Symbol</th>
            <th>Market</th>
            <th>Name</th>
            <th>Watch Graph</th>
        </tr>
        </thead>
        <tbody>
        {% if Kosdaq_list %}
        <tr>
            <td>{{ Kosdaq_list.Symbol}}</td>
            <td>{{ Kosdaq_list.Market }}</td>
            <td>{{ Kosdaq_list.Name }}</td>
            <td><a href="{% url 'pybo:graph' Kosdaq_list.Symbol %}"><string>그래프 보기</string></a></td>
        </tr>
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>No.</th>
            <th>날짜</th>
            <th>시가</th>
            <th>종가</th>
            <th>고가</th>
            <th>저가</th>
            <th>변화율</th>
            <th>거래량</th>
        </tr>
        </thead>
        <tbody>
        {% if d %}
        {% for finance in d %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ finance.Date}}</td>
            <td>{{ finance.Open }}</td>
            <td>{{ finance.Close }}</td>
            <td>{{ finance.High }}</td>
            <td>{{ finance.Low }}</td>
            <td>{{ finance.Volume }}</td>
            {% if finance.Change > 0 %}
            <td class="text-danger">{{ finance.Change}}%</td>
            {% else %}
            <td class="text-primary" >{{ finance.Change}}%</td>
            {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if d.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ d.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in d.paginator.page_range %}
        {% if page_number >= d.number|add:-5 and page_number <= d.number|add:5 %}
            {% if page_number == d.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ d.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}

templates/pybo/kospi.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<form action="" method='GET'>
    <div class="row justify-content-end my-3" style="margin-bottom:15px;">
        <div class="col-4 input-group">
            <div class="input-group">
                <input type="text" class="form-control" name="search_key" value="{{ search_key }}"
                    placeholder="looking for...">
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search">
                </span>
            </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
</form>

<div class="row">
    <div id="video_list_search" class="col-md-12">
        {% for video in video_list %}
        <a href="/video/{{ video.id }}">
            <h4>{{ video.title }}</h4>
        </a>
        {% endfor %}
    </div>
</div>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>No.</th>
            <th>종목번호</th>
            <th>시장</th>
            <th>회사명</th>
        </tr>
        </thead>
        <tbody>
        {% if kospi_list %}
        {% for kospi in kospi_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ kospi.Symbol}}</td>
            <td>{{ kospi.Market }}</td>
            <td><a href="{% url 'pybo:kospi_detail' kospi.Symbol %}">{{ kospi.Name }}</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if kospi_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ kospi_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in kospi_list.paginator.page_range %}
        {% if page_number >= kospi_list.number|add:-5 and page_number <= kospi_list.number|add:5 %}
            {% if page_number == kospi_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if kospi_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ kospi_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
         {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>내용</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href = "{% url 'pybo:question_create'%}" class="btn btn-primary">질문등록</a>
</div>

{% endblock %}