common/urls.py
from django.contrib import auth
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/',views.signup, name = 'signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', views.index , name ='index'),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail , name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name = 'question_create'),
    #path('finance/', views.finance, name = 'finance'),
    #path('finance/<int:finance_id>/', views.finance_detail, name = 'finance_detail'),
    path('kospi/', views.kospi , name = 'kospi'),
    path('kosdaq/', views.kosdaq , name = 'kosdaq'),
    path('Risk/', views.risk, name='risk'),
    path('kospi/<int:kospi_id>/', views.kospi_detail , name = 'kospi_detail'),
    path('kosdaq/<int:kosdaq_id>/', views.kosdaq_detail , name = 'kosdaq_detail'),    
    path('kospi/<int:id>/graph', views.graph , name = 'graph'),
    path('kosdaq/<int:id>/graph', views.graph , name = 'graph'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-2.4.0.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.4.0.min.css" rel="stylesheet" type="text/css">
    
    <!-- pybo CSS -->
    <title>Finance Data</title>
</head>

<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}" ></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}" ></script>
{% include "footer.html" %}
</body>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.0.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.0.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.4.0.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.4.0.min.js"></script>
{{script| safe}}
{{script1| safe}}
{{script2| safe}}
{{script3| safe}}



</html>

templates/footer.html
<!-- footer-->>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="https://blog.kakaocdn.net/dn/baoW1W/btqx8AAZBkU/GnfKQeTNrmqf4BJKLOKugK/img.jpg" alt="인포섹" width="370" height="142" />
      </div>
      <div class="col-6 col-md">
        <h5>Teammate</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">배준현</a></li>
          <li><a class="text-muted" href="#">방준원</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
        </ul>
      </div>
    </div>
  </footer>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Finance Data</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <a class="nav-link" href="{% url 'pybo:kospi' %}">Kospi</a>
        <a class="nav-link" href="{% url 'pybo:kosdaq' %}">Kosdaq</a>
        <a class="nav-link" href="{% url 'pybo:risk' %}">Risk Index</a>
        <ul class="navbar-nav">
            <li class="nav-item ">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
            {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>